version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      microsoft-extensions-di:
        patterns:
          - "Microsoft.Extensions.DependencyInjection*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
